on: [push, pull_request]

name: AOC2022

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.65.0
          override: true

      - name: Test AOC2022 Day 01 Part 1
        uses: actions-rs/cargo@v1
        working-directory: ./
        with:
          command: test
          args: --manifest-path=AOC2022/day01/day01a/Cargo.toml

      - name: Test AOC2022 Day 01 Part 2
        uses: actions-rs/cargo@v1
        working-directory: ./
        with:
          command: test
          args: --manifest-path=AOC2022/day01/day01b/Cargo.toml