on: [push, pull_request]

name: AOC2022

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.65.0
          override: true

      - name: Test AOC2022 workspace
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --manifest-path=AOC2022/Cargo.toml